version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/' # Location of package manifests
      schedule:
          interval: 'daily'
      assignees:
          - 'kdev'
      commit-message:
          prefix: 'chore'
          include: 'scope'
      reviewers:
          - 'kdev'
      open-pull-requests-limit: 10
      target-branch: 'dev'
      groups:
          typescript-eslint:
              patterns:
                  - '@typescript-eslint/*'
          prisma:
              patterns:
                  - '@prisma/client'
                  - 'prisma'
          types:
              patterns:
                  - '@types/*'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      assignees:
          - 'kdev'
      commit-message:
          prefix: 'chore'
          include: 'scope'
      reviewers:
          - 'kdev'
      target-branch: 'dev'

    - package-ecosystem: 'docker'
      directory: '/'
      schedule:
          interval: 'daily'
      assignees:
          - 'kdev'
      commit-message:
          prefix: 'chore'
          include: 'scope'
      target-branch: 'dev'
