version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/' # Location of package manifests
      schedule:
          interval: 'daily'
      assignees:
          - 'kdev'
      commit-message:
          prefix: 'chore'
          include: 'scope'
      reviewers:
          - 'kdev'
      open-pull-requests-limit: 10
      target-branch: 'beta'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      assignees:
          - 'kdev'
      commit-message:
          prefix: 'chore'
          include: 'scope'
      reviewers:
          - 'kdev'
      target-branch: 'beta'
      
    - package-ecosystem: 'docker'
      directory: '/'
      schedule:
          interval: 'daily'
      assignees:
         - 'kdev'
      commit-message:
          prefix: 'chore'
          include: 'scope'
      target-branch: 'beta'
    
