version: '3.7'

environment:
    PG_USER: postgresql
    PG_PASSWORD: supersecret
    PG_DB: community-service

services:
    postgres:
        image: postgres:14.2
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DB}

    community-service:
        build: .
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
            DISCORD_TOKEN: # discord token
            DISCORD_CLIENT_ID: # some client id
            # DISCORD_DEV_GUILD_ID: NOT USED IN PROD
            DATABASE_URL: postgresql://${PG_USER}:${PG_PASSWORD}@postgres:5432/${PG_DB}?schema=public
