version: '3.7'

services:
    postgres:
        image: postgres:16
        env_file:
            - prod.env
        volumes:
            - ./data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 2

    community-service:
        build: .
        depends_on:
            postgres:
                condition: service_healthy
        ports:
            - '3000:3000'
        env_file:
            - prod.env
