allowBuilds:
  '@prisma/engines': true
  bufferutil: true
  esbuild: true
  node-libcurl: true
  prisma: true
  utf-8-validate: true
  zlib-sync: true
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bufferutil
  - esbuild
  - node-libcurl
  - prisma
  - utf-8-validate
  - zlib-sync
