name: Build
on:
    push:
    workflow_dispatch:

jobs:
    build-project:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        env:
            PG_USER: postgres
            PG_PW: supersecret
            PG_DB: community-service-test
            DATABASE_URL: postgres://postgres:supersecret@localhost:5432/community-service-test?schema=public

        services:
            postgres:
                image: postgres:14.2
                env:
                    POSTGRES_USER: ${ PG_USER }
                    POSTGRES_PASSWORD: ${ PG_PW }
                    POSTGRES_DB: ${ PG_DB }
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Log Database URL
              run: echo "Database URL $DATABASE_URL; PG_USER $PG_USER; PG_PW $PG_PW; PG_DB $PG_DB"
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Run API tests
              run: npm run test:api
