name: Release workflow
on:
    push:
        branches:
            - main
    repository_dispatch:

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    test:
        name: '🧪 Test and lint'
        uses: ./.github/workflows/development.yml

    release-please:
        needs: test
        runs-on: ubuntu-latest

        steps:
            - name: Generate Token
              id: app-token
              uses: actions/create-github-app-token@v3
              with:
                  app-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: '☁️ Checkout repository'
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
                  persist-credentials: false
                  token: ${{ steps.app-token.outputs.token }}

            - name: '🔧 Setup Node.js'
              uses: actions/setup-node@v6
              with:
                  node-version: '24'

            - uses: googleapis/release-please-action@v4
              with:
                  token: ${{ steps.app-token.outputs.token }}
                  config-file: release-please-config.json
                  manifest-file: .release-please-manifest.json
